<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ComuniSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('comuni')->delete();


        $comuni = array(
            array('id' =>6, 'regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Pescara'),
            array('id' =>7, 'regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Montesilvano'),
            array('id' =>8, 'regione' =>'Abruzzo', 'provincia' =>'Pescara', 'comune' => 'Spoltore'),
            array('id' =>9, 'regione' =>'Abruzzo', 'provincia' => 'L\'Aquila', 'comune' => 'L\'Aquila'),
            array('id' =>10, 'regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Pescasseroli'),
            array('id' =>11, 'regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Ovindoli'),
            array('id' =>12, 'regione' =>'Abruzzo', 'provincia' =>'L\'Aquila', 'comune' => 'Coppito'),
            array('id' =>13, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Altino'),
            array('id' =>14, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Archi'),
            array('id' =>15, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Ari'),
            array('id' =>16, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Arielli'),
            array('id' =>13, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Atessa'),
            array('id' =>14, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Bomba'),
            array('id' =>15, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Borrello'),
            array('id' =>16, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Bucchianico'),
            array('id' =>17, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Canosa Sannita'),
            array('id' =>18, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Carpineto Sinello'),
            array('id' =>19, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Carunchio'),
            array('id' =>20, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casacanditella'),
            array('id' =>21, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casalanguida'),
            array('id' =>22, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casalbordino'),
            array('id' =>23, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casalincontrada'),
            array('id' =>24, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Casoli'),
            array('id' =>25, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Castel Frentano'),
            array('id' =>26, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Castelguidone'),
            array('id' =>27, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Castiglione Messer M.'),
            array('id' =>28, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Calenza sul Trigno'),
            array('id' =>29, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Chieti'),
            array('id' =>30, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Civitaluparella'),
            array('id' =>31, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Civitella Messer M.'),
            array('id' =>32, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Colledimacine'),
            array('id' =>33, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Colledimezzo'),
            array('id' =>34, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Crecchio'),
            array('id' =>35, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Cupello'),
            array('id' =>36, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Dogliola'),
            array('id' =>37, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fallo'),
            array('id' =>38, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fara Filiorum Petri'),
            array('id' =>39, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fara San Martino'),
            array('id' =>40, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Filetto'),
            array('id' =>41, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fossacesia'),
            array('id' =>42, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fraine'),
            array('id' =>43, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Francavilla al Mara'),
            array('id' =>44, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Fresagrandinaria'),
            array('id' =>45, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Frisa'),
            array('id' =>46, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Furci'),
            array('id' =>47, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Gamberale'),
            array('id' =>48, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Gessopalena'),
            array('id' =>49, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Gissi'),
            array('id' =>50, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Giuliano Teatino'),
            array('id' =>51, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Guardiagrele'),
            array('id' =>52, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Guilmi'),
            array('id' =>53, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Lama dei Peligni'),
            array('id' =>54, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Lanciano'),
            array('id' =>55, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Lentella'),
            array('id' =>56, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Lettopalena'),
            array('id' =>57, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Liscia'),
            array('id' =>58, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Miglianico'),
            array('id' =>59, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Montazzoli'),
            array('id' =>60, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Montebello sul Sangro'),
            array('id' =>61, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Monteferrante'),
            array('id' =>62, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Montelapiano'),
            array('id' =>63, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Montenerodomo'),
            array('id' =>64, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Monteodorisio'),
            array('id' =>65, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Mozzagrogna'),
            array('id' =>66, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Orsogna'),
            array('id' =>67, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Ortona'),
            array('id' =>68, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Paglieta'),
            array('id' =>69, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Palena'),
            array('id' =>70, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Palmoli'),
            array('id' =>71, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Palombaro'),
            array('id' =>72, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pennadomo'),
            array('id' =>73, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pennadipiemonte'),
            array('id' =>74, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Perano'),
            array('id' =>75, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pietraferrazzana'),
            array('id' =>76, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pizzoferrato'),
            array('id' =>77, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Poggiofiorito'),
            array('id' =>78, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pollutri'),
            array('id' =>79, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Pretoro'),
            array('id' =>80, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Quadri'),
            array('id' =>81, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Rapino'),
            array('id' =>82, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Ripa Teatina'),
            array('id' =>83, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Rocca San Giovanni'),
            array('id' =>84, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Roccamontepiano'),
            array('id' =>85, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Roccascalegna'),
            array('id' =>86, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Roccaspinalveti'),
            array('id' =>87, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Roio del Sangro'),
            array('id' =>88, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Rosello'),
            array('id' =>89, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Buono'),
            array('id' =>90, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Giovanni Lipioni'),
            array('id' =>91, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Giovanni Teatino'),
            array('id' =>92, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Martino sulla M.'),
            array('id' =>93, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Salvo'),
            array('id' =>94, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'San Vito Chietino'),
            array('id' =>95, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Sant\'Eusanio del Sangro'),
            array('id' =>96, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Santa Maria Imbaro'),
            array('id' =>97, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Scerni'),
            array('id' =>98, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Schiavi di Abruzzo'),
            array('id' =>99, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Taranta Peligna'),
            array('id' =>100, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Tollo'),
            array('id' =>101, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Torino di Sangro'),
            array('id' =>102, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Tornareccio'),
            array('id' =>103, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Torrebruna'),
            array('id' =>104, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Torrevecchia Teatina'),
            array('id' =>105, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Torricella Peligna'),
            array('id' =>106, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Treglio'),
            array('id' =>107, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Tufillo'),
            array('id' =>108, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Vacri'),
            array('id' =>109, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Vasto'),
            array('id' =>110, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Villa Santa Maria'),
            array('id' =>111, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Villalfonsina'),
            array('id' =>112, 'regione' =>'Abruzzo', 'provincia' =>'Chieti', 'comune' => 'Villamagna'),
            array('id' =>113, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Alba Adriatica'),
            array('id' =>114, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Ancarano'),
            array('id' =>115, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Arsita'),
            array('id' =>116, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Atri'),
            array('id' =>117, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Basciano'),
            array('id' =>118, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Bellante'),
            array('id' =>119, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Bisenti'),
            array('id' =>120, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Campli'),
            array('id' =>121, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Canzano'),
            array('id' =>122, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castel Castagna'),
            array('id' =>123, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castellalto'),
            array('id' =>124, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castelli'),
            array('id' =>125, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castiglione Messer M.'),
            array('id' =>126, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Castilenti'),
            array('id' =>127, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Cellino Attanasio'),
            array('id' =>128, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Carmignano'),
            array('id' =>129, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Civitella del Tronto'),
            array('id' =>130, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Colledara'),
            array('id' =>131, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Colonnella'),
            array('id' =>132, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Controguerra'),
            array('id' =>133, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Corropoli'),
            array('id' =>134, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Cortino'),
            array('id' =>135, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Crognaleto'),
            array('id' =>136, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Fano Adriano'),
            array('id' =>137, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Giualianova'),
            array('id' =>138, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Isola del Gran Sasso d\'Italia'),
            array('id' =>139, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Martinsicuro'),
            array('id' =>140, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Montefino'),
            array('id' =>141, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Montorio al Vomano'),
            array('id' =>142, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Morro d\'Oro'),
            array('id' =>143, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Mosciano Sant\'Angelo'),
            array('id' =>144, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Nereto'),
            array('id' =>145, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Notaresco'),
            array('id' =>146, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Penna Sant\'Andrea'),
            array('id' =>147, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Pietracamela'),
            array('id' =>148, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Pineto'),
            array('id' =>149, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Rocca Santa Maria'),
            array('id' =>150, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Roseto degli Abruzzi'),
            array('id' =>151, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Sant\'Egidio alla Vibrata'),
            array('id' =>152, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Sant\'Omero'),
            array('id' =>153, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Silvi'),
            array('id' =>154, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Teramo'),
            array('id' =>155, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Torano Nuovo'),
            array('id' =>156, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Torricella Sicura'),
            array('id' =>157, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Tortoreto'),
            array('id' =>158, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Tossicia'),
            array('id' =>159, 'regione' =>'Abruzzo', 'provincia' =>'Teramo', 'comune' => 'Valle Castellana'),
            
        );


        DB::table('comuni')->insert($comuni);
    }
}
